### ISSUE TITLE
Test Suite Failures

### ISSUE THREAD

**Issue by pbulsink** [SCasanova/f1dataR#216]
Failures seen in recent PR unrelated to the new code being committed. See failures in #211,#213 (specifically something like https://github.com/SCasanova/f1dataR/actions/runs/7597232191/job/20691818003?pr=213)

```
Error ('test-load_session_laps.R:18:3'): load session laps works ────────────
<python.builtin.AttributeError/python.builtin.Exception/python.builtin.BaseException/python.builtin.object/error/condition>
Error in `py_run_string_impl(code, local, convert)`: AttributeError: 'NoneType' object has no attribute 'name'
Run `reticulate::py_last_error()` for details.
Backtrace:
    ▆
 1. └─f1dataR (local) `<fn>`(season = 2022, round = "bahrain", session = "Q", add_weather = TRUE)
 2.   └─reticulate::py_run_string(...) at f1dataR/R/load_session_laps.R:65:5
 3.     └─reticulate:::py_run_string_impl(code, local, convert)
```

Fails in nearly every R CMD CHK test and code coverage.

**Comment by pbulsink** [comment]
@SCasanova Do you want this fixed before merging #211?

**Comment by SCasanova** [comment]
Not necessarily. I'm ok with the extra functionality if it's just a bug

**Comment by pbulsink** [comment]
I might merge #213 as well, it'll only help with tracking down this issue.
